import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const catalogRecords = sqliteTable('catalog_records', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  dbNumber: text('db_number').notNull().default(''),
  bibliographicId: text('bibliographic_id').notNull().default(''),
  inventoryNumber: text('inventory_number').notNull().default(''),
  recordState: text('record_state').notNull().default('В фонде'),
  recordType: text('record_type').notNull().default(''),
  bibliographicLevel: text('bibliographic_level').notNull().default(''),
  author: text('author').notNull().default(''),
  title: text('title').notNull().default(''),
  titleFull: text('title_full').notNull().default(''),
  edition: text('edition').notNull().default(''),
  publicationPlace: text('publication_place').notNull().default(''),
  publisher: text('publisher').notNull().default(''),
  publicationYear: text('publication_year').notNull().default(''),
  physicalDescription: text('physical_description').notNull().default(''),
  series: text('series').notNull().default(''),
  subjects: text('subjects').notNull().default(''),
  keywords: text('keywords').notNull().default(''),
  classification: text('classification').notNull().default(''),
  shelfmark: text('shelfmark').notNull().default(''),
  notes: text('notes').notNull().default(''),
  location: text('location').notNull().default(''),
  accountingStatus: text('accounting_status').notNull().default(''),
  fundType: text('fund_type').notNull().default(''),
  invoice: text('invoice').notNull().default(''),
  inventoryMode: text('inventory_mode').notNull().default(''),
  registrationDate: text('registration_date').notNull().default(''),
  writeoffDate: text('writeoff_date').notNull().default(''),
  writeoffAct: text('writeoff_act').notNull().default(''),
  writeoffReason: text('writeoff_reason').notNull().default(''),
  loanStatus: text('loan_status').notNull().default('В наличии'),
  readerId: text('reader_id').notNull().default(''),
  lastLoanDate: text('last_loan_date').notNull().default(''),
  lastReturnDate: text('last_return_date').notNull().default(''),
  loanCount: integer('loan_count').notNull().default(0),
  marcFieldsJson: text('marc_fields_json').notNull().default(''),
  rawMarc: text('raw_marc').notNull().default(''),
  verified: integer('verified', { mode: 'boolean' }).notNull().default(false),
  verifiedBy: text('verified_by'),
  verifiedAt: text('verified_at'),
  deletedAt: text('deleted_at'),
  deletedBy: text('deleted_by'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
}, (table) => [
  index('idx_catalog_db_number').on(table.dbNumber),
  index('idx_catalog_inventory_number').on(table.inventoryNumber),
  index('idx_catalog_author').on(table.author),
  index('idx_catalog_title').on(table.title),
  index('idx_catalog_deleted_at').on(table.deletedAt),
]);

export const loans = sqliteTable('loans', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  recordId: integer('record_id').references(() => catalogRecords.id),
  dbNumber: text('db_number').notNull().default(''),
  readerId: text('reader_id').notNull().default(''),
  readerNote: text('reader_note').notNull().default(''),
  loanDate: text('loan_date').notNull().default(''),
  returnDate: text('return_date').notNull().default(''),
  returnNote: text('return_note').notNull().default(''),
  quantity: integer('quantity').notNull().default(1),
  issuedBy: text('issued_by').notNull().default(''),
  returnedBy: text('returned_by').notNull().default(''),
  createdAt: text('created_at').notNull().default(''),
}, (table) => [
  index('idx_loans_record_id').on(table.recordId),
  index('idx_loans_active').on(table.recordId, table.returnDate),
]);

export const auditLog = sqliteTable('audit_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  recordId: integer('record_id').references(() => catalogRecords.id),
  action: text('action').notNull(),
  changesJson: text('changes_json').notNull().default('{}'),
  actorId: text('actor_id').notNull(),
  actorEmail: text('actor_email').notNull(),
  createdAt: text('created_at').notNull(),
}, (table) => [index('idx_audit_record_id').on(table.recordId)]);
